{"uuid": "0e4a3431-26fc-49e8-b1b1-04928b235fd6", "children": ["97c5f0af-d6b2-469a-9a01-0173124557ce"], "befores": [{"name": "create_and_delete_user", "status": "failed", "statusDetails": {"message": "AssertionError: Пользователь не был создан, код ответа: 403, текст: {\"success\":false,\"message\":\"User already exists\"}\nassert 403 == 200\n +  where 403 = <Response [403]>.status_code\n", "trace": "  File \"/Users/anastasiya.anikina/PycharmProjects/Diplom_2/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/anastasiya.anikina/PycharmProjects/Diplom_2/.venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/anastasiya.anikina/PycharmProjects/Diplom_2/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anastasiya.anikina/PycharmProjects/Diplom_2/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anastasiya.anikina/PycharmProjects/Diplom_2/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/anastasiya.anikina/PycharmProjects/Diplom_2/conftest.py\", line 19, in create_and_delete_user\n    assert create_response.status_code == 200, f\"Пользователь не был создан, код ответа: {create_response.status_code}, текст: {create_response.text}\"\n"}, "start": 1729349446689, "stop": 1729349446859}], "start": 1729349446689, "stop": 1729349446899}